### ISSUE TITLE
BUG: Crash when launching any profile. Android 14.

### ISSUE THREAD

**Issue by OBrein** [xchacha20-poly1305/husi#18]
## Describe the problem

Expected behavior:
Crash when launching any profile.
Actual behavior:

## How to reproduce
Galaxy Fold 5, Android 14. Just start any VPN: shadowsocks, vless, hysteria etc.
Provide helpful screenshots, videos, text descriptions, subscription links, etc.

## log
Cl12024/01/29 06:25:39 [Error] [CrashHandler] Thread[main,5,main]
2024/01/29 06:25:39 [Error] [CrashHandler] java.lang.RuntimeException: Unable to start service io.nekohasekai.sagernet.bg.ProxyService@1bbc5b2 with Intent { cmp=fr.husi/io.nekohasekai.sagernet.bg.ProxyService }: java.lang.SecurityException: fr.husi: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5286)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2531)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8913)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.lang.SecurityException: fr.husi: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
	at android.os.Parcel.createException(Parcel.java:3053)
	at android.os.Parcel.readException(Parcel.java:3036)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6137)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1913)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1853)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:784)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$DefaultImpls.onStartCommand(SourceFile:134)
	at io.nekohasekai.sagernet.bg.ProxyService.onStartCommand(Unknown Source:0)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5268)
	... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:16590)
	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:11530)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2928)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3195)
	at android.os.Binder.execTransactInternal(Binder.java:1375)
If you have logs, please upload them. Please see the detailed steps for exporting logs in the documentation.

**Comment by OBrein** [comment]
> Please test the APK in https://github.com/xchacha20-poly1305/husi/actions/runs/7720937048

Still crushing  in this apk
2024/01/31 04:52:14 [Error] [CrashHandler] Thread[main @coroutine#6,5,main]
2024/01/31 04:52:14 [Error] [CrashHandler] android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{7bb9871 27349:fr.husi.debug:bg/u0a458} targetSDK=34
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4882)
	at android.os.Parcel.readParcelable(Parcel.java:4864)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3064)
	at android.os.Parcel.createException(Parcel.java:3053)
	at android.os.Parcel.readException(Parcel.java:3036)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7214)
	at android.app.Service.startForeground(Service.java:775)
	at io.nekohasekai.sagernet.bg.ServiceNotification$show$2.invoke(ServiceNotification.kt:186)
	at io.nekohasekai.sagernet.bg.ServiceNotification$show$2.invoke(ServiceNotification.kt:186)
	at io.nekohasekai.sagernet.bg.ServiceNotification.useBuilder(ServiceNotification.kt:127)
	at io.nekohasekai.sagernet.bg.ServiceNotification.show(ServiceNotification.kt:186)
	at io.nekohasekai.sagernet.bg.ServiceNotification.access$show(ServiceNotification.kt:38)
	at io.nekohasekai.sagernet.bg.ServiceNotification$2.invokeSuspend(ServiceNotification.kt:145)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:68)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:375)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at io.nekohasekai.sagernet.ktx.AsyncsKt.runOnMainDispatcher(Asyncs.kt:29)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$DefaultImpls.onStartCommand(BaseService.kt:361)
	at io.nekohasekai.sagernet.bg.VpnService.onStartCommand(VpnService.kt:82)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5268)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2531)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8913)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineId(6), "coroutine#6":StandaloneCoroutine{Cancelling}@6b691fd, Dispatchers.Main.immediate]

**Comment by OBrein** [comment]
https://github.com/xchacha20-poly1305/husi/actions/runs/7720937048
Still crushing too

2024/01/31 04:57:46 [Error] [CrashHandler] Thread[main @coroutine#6,5,main]
2024/01/31 04:57:46 [Error] [CrashHandler] android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{1af049b 2278:fr.husi.debug:bg/u0a458} targetSDK=34
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4882)
	at android.os.Parcel.readParcelable(Parcel.java:4864)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3064)
	at android.os.Parcel.createException(Parcel.java:3053)
	at android.os.Parcel.readException(Parcel.java:3036)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7214)
	at android.app.Service.startForeground(Service.java:775)
	at io.nekohasekai.sagernet.bg.ServiceNotification$show$2.invoke(ServiceNotification.kt:186)
	at io.nekohasekai.sagernet.bg.ServiceNotification$show$2.invoke(ServiceNotification.kt:186)
	at io.nekohasekai.sagernet.bg.ServiceNotification.useBuilder(ServiceNotification.kt:127)
	at io.nekohasekai.sagernet.bg.ServiceNotification.show(ServiceNotification.kt:186)
	at io.nekohasekai.sagernet.bg.ServiceNotification.access$show(ServiceNotification.kt:38)
	at io.nekohasekai.sagernet.bg.ServiceNotification$2.invokeSuspend(ServiceNotification.kt:145)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:68)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:375)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at io.nekohasekai.sagernet.ktx.AsyncsKt.runOnMainDispatcher(Asyncs.kt:29)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$DefaultImpls.onStartCommand(BaseService.kt:361)
	at io.nekohasekai.sagernet.bg.VpnService.onStartCommand(VpnService.kt:82)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5268)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2531)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8913)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineId(6), "coroutine#6":StandaloneCoroutine{Cancelling}@f250ac1, Dispatchers.Main.immediate]
------
Config shadowsocks here
-----
2024/01/31 04:57:46 [Debug] [TrafficLooper] traffic count proxy to 1
2024/01/31 04:57:48 [Error] [CrashHandler] Thread[main @coroutine#4,5,main]
2024/01/31 04:57:48 [Error] [CrashHandler] android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{70c132f 2631:fr.husi.debug:bg/u0a458} targetSDK=34
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4882)
	at android.os.Parcel.readParcelable(Parcel.java:4864)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3064)
	at android.os.Parcel.createException(Parcel.java:3053)
	at android.os.Parcel.readException(Parcel.java:3036)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7214)
	at android.app.Service.startForeground(Service.java:775)
	at io.nekohasekai.sagernet.bg.ServiceNotification$show$2.invoke(ServiceNotification.kt:186)
	at io.nekohasekai.sagernet.bg.ServiceNotification$show$2.invoke(ServiceNotification.kt:186)
	at io.nekohasekai.sagernet.bg.ServiceNotification.useBuilder(ServiceNotification.kt:127)
	at io.nekohasekai.sagernet.bg.ServiceNotification.show(ServiceNotification.kt:186)
	at io.nekohasekai.sagernet.bg.ServiceNotification.access$show(ServiceNotification.kt:38)
	at io.nekohasekai.sagernet.bg.ServiceNotification$2.invokeSuspend(ServiceNotification.kt:145)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:68)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:375)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at io.nekohasekai.sagernet.ktx.AsyncsKt.runOnMainDispatcher(Asyncs.kt:29)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$DefaultImpls.onStartCommand(BaseService.kt:361)
	at io.nekohasekai.sagernet.bg.VpnService.onStartCommand(VpnService.kt:82)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5268)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2531)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8913)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineId(4), "coroutine#4":StandaloneCoroutine{Cancelling}@43ffe90, Dispatchers.Main.immediate]

**Comment by OBrein** [comment]
https://github.com/xchacha20-poly1305/husi/actions/runs/7720937048
Still crushing

Log:
2024/01/31 04:57:46 [Error] [CrashHandler] Thread[main @coroutine#6,5,main]
2024/01/31 04:57:46 [Error] [CrashHandler] android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{1af049b 2278:fr.husi.debug:bg/u0a458} targetSDK=34
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4882)
	at android.os.Parcel.readParcelable(Parcel.java:4864)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3064)
	at android.os.Parcel.createException(Parcel.java:3053)
	at android.os.Parcel.readException(Parcel.java:3036)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7214)
	at android.app.Service.startForeground(Service.java:775)
	at io.nekohasekai.sagernet.bg.ServiceNotification$show$2.invoke(ServiceNotification.kt:186)
	at io.nekohasekai.sagernet.bg.ServiceNotification$show$2.invoke(ServiceNotification.kt:186)
	at io.nekohasekai.sagernet.bg.ServiceNotification.useBuilder(ServiceNotification.kt:127)
	at io.nekohasekai.sagernet.bg.ServiceNotification.show(ServiceNotification.kt:186)
	at io.nekohasekai.sagernet.bg.ServiceNotification.access$show(ServiceNotification.kt:38)
	at io.nekohasekai.sagernet.bg.ServiceNotification$2.invokeSuspend(ServiceNotification.kt:145)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:68)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:375)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at io.nekohasekai.sagernet.ktx.AsyncsKt.runOnMainDispatcher(Asyncs.kt:29)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$DefaultImpls.onStartCommand(BaseService.kt:361)
	at io.nekohasekai.sagernet.bg.VpnService.onStartCommand(VpnService.kt:82)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5268)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2531)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8913)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineId(6), "coroutine#6":StandaloneCoroutine{Cancelling}@f250ac1, Dispatchers.Main.immediate]
------
Cinfig Shadowsocks here
------
2024/01/31 04:57:46 [Debug] [TrafficLooper] traffic count proxy to 1
2024/01/31 04:57:48 [Error] [CrashHandler] Thread[main @coroutine#4,5,main]
2024/01/31 04:57:48 [Error] [CrashHandler] android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{70c132f 2631:fr.husi.debug:bg/u0a458} targetSDK=34
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4882)
	at android.os.Parcel.readParcelable(Parcel.java:4864)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3064)
	at android.os.Parcel.createException(Parcel.java:3053)
	at android.os.Parcel.readException(Parcel.java:3036)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7214)
	at android.app.Service.startForeground(Service.java:775)
	at io.nekohasekai.sagernet.bg.ServiceNotification$show$2.invoke(ServiceNotification.kt:186)
	at io.nekohasekai.sagernet.bg.ServiceNotification$show$2.invoke(ServiceNotification.kt:186)
	at io.nekohasekai.sagernet.bg.ServiceNotification.useBuilder(ServiceNotification.kt:127)
	at io.nekohasekai.sagernet.bg.ServiceNotification.show(ServiceNotification.kt:186)
	at io.nekohasekai.sagernet.bg.ServiceNotification.access$show(ServiceNotification.kt:38)
	at io.nekohasekai.sagernet.bg.ServiceNotification$2.invokeSuspend(ServiceNotification.kt:145)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:68)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:375)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at io.nekohasekai.sagernet.ktx.AsyncsKt.runOnMainDispatcher(Asyncs.kt:29)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$DefaultImpls.onStartCommand(BaseService.kt:361)
	at io.nekohasekai.sagernet.bg.VpnService.onStartCommand(VpnService.kt:82)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5268)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2531)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8913)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineId(4), "coroutine#4":StandaloneCoroutine{Cancelling}@43ffe90, Dispatchers.Main.immediate]
